[workspace]
members = [
  "midway-exercise",
  "tut3-basic-concepts",
  "tut4-ownership",
  "tut5-structs",
  "tut6-enums-and-patterns",
  "tut7-modules",
  "tut13-func-lang-features",
  "tut15-smart-pointers",
  "tut16-concurrency",
  "thread-assignment",
  "leptos-prac"
]
