[package]
name = "leptos_prac"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
leptos = "0.2"
reqwasm = "0.5.0"
log = "0.4"
console_log = "1"
console_error_panic_hook = "0.1.7"

[dev-dependencies]
wasm-bindgen-test = "0.3.0"
